name: Node CI

on: [push]

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [15.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node: ${{ matrix.node }}
      - name: Setup yarn
        run: npm i -g yarn

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

        env:
          CI: true
      - name: Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1.0.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
